# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9782e116b34f7ba9a11b13ff20f5beca"
name = "after-purchase-referral"
handle = "after-purchase-referral"
application_url = "https://creek-samuel-paragraphs-cost.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://creek-samuel-paragraphs-cost.trycloudflare.com/auth/callback",
  "https://creek-samuel-paragraphs-cost.trycloudflare.com/auth/shopify/callback",
  "https://creek-samuel-paragraphs-cost.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
